### PR TITLE
Add attachment basedirs to repair_settings

### PR DESCRIPTION
**Pull request by BrickOzp**
Attachment basedir paths also needs to be updated.

Signed-off-by: Oscar Rydhé <oscar.rydhe@gmail.com>

### CODE REVIEW

**Review by sbulen — APPROVED** [review]
LGTM - tested with a variety of folder setups in 2.1.

**Comment by sbulen** [comment]
Actually, I was just using it on a 2.1 forum and got the following...

Forum was migrated from 2.0, & has never had base directories:
image

**Comment by BrickOzp** [comment]
Thanks for testing @sbulen 
Turns out there was no check if a setting existed so this error could happen for any of the settings.

**Comment by sbulen** [comment]
That's because none of the others are optional.

I've used this tool hundreds of times in all different smf versions & have never seen that.

So thanks for fixing!

**Review by sbulen — CHANGES_REQUESTED** [review]
I don’t think we want to skip all settings if not present....

Required settings must remain required...

The basedir setting is required only under some circumstances.

**Comment by sbulen** [comment]
**_As an example, without an avatar directory, this is the old behavior:_**
no_avatar_url_old

**_Vs this is how it behaves with this PR:_**
no_avatar_url_new

**Comment by sbulen** [comment]
You can either go with a "show it when present" behavior, or maybe a bit better, "show it when basedir specified in the options".  

I'm not totally familiar with basedirs, I think they may be required when automanage_attachments isn't empty???  Not sure, that would require some research & testing...

**Review by sbulen — APPROVED** [review]

**Comment by sbulen** [comment]
Works great now, thanks.  Let's give it another day or so of airtime to see if anyone else wants to pipe in. 

It's possible SleePy would want the version incremented?  He has asked for that before. Might be smart to do that before we merge.

**Comment by jdarwood007** [comment]
I can send a quick update for the version when we update the downloads page.  Its supposed to help us indicate if people have a old version of the tool.  Both the date and version are used.  Version to indicate revisions to the code, the date to indicate the published date.

**Comment by sbulen** [comment]
So should we merge this now?

**Pull request merged**
